### ISSUE TITLE
SyntaxError

### ISSUE THREAD

**Issue by NavodAnusha** [ArushiSinghal/Automatic-Instrument-Identification#2]
D:\Documents\BSC\Galeen\Advance programe>python svm_audio.py features.csv
  File "svm_audio.py", line 22
    print C_range
                ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(C_range)?

**Comment by ArushiSinghal** [comment]
Depends on what are you using python2 or python3

**Comment by NavodAnusha** [comment]
> Depends on what are you using python2 or python3

I have a python 3.7

**Comment by ArushiSinghal** [comment]
Then you should add parenthesis.
